name: demo_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.6
  camera: ^0.10.0+4
  image_picker: ^0.8.5+3
  path_provider: ^2.1.2
  google_mlkit_barcode_scanning: 0.10.0
  google_mlkit_text_recognition: ^0.11.0
  lottie: ^2.6.0
  share_plus: ^7.2.1
  flutter_tts: ^3.8.2
  package_info_plus: 8.3.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/animations/loader.json
