// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmjOram0hmHSXEHpYhpe0ldl_qqKo1_Sg',
    appId: '1:954030564160:web:bc3b6026d1358b37c2d0a5',
    messagingSenderId: '954030564160',
    projectId: 'ai-text-digitization',
    authDomain: 'ai-text-digitization.firebaseapp.com',
    storageBucket: 'ai-text-digitization.firebasestorage.app',
    measurementId: 'G-FP314Z7V6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtY5449DdNWRnsdCpaxTZltaMMKadXAtw',
    appId: '1:954030564160:android:b6a4fc2fec3230aac2d0a5',
    messagingSenderId: '954030564160',
    projectId: 'ai-text-digitization',
    storageBucket: 'ai-text-digitization.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTs6LO5sDh8i78VoK6hJ-XZDc8nTV58aM',
    appId: '1:954030564160:ios:264140aad19967c1c2d0a5',
    messagingSenderId: '954030564160',
    projectId: 'ai-text-digitization',
    storageBucket: 'ai-text-digitization.firebasestorage.app',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTs6LO5sDh8i78VoK6hJ-XZDc8nTV58aM',
    appId: '1:954030564160:ios:264140aad19967c1c2d0a5',
    messagingSenderId: '954030564160',
    projectId: 'ai-text-digitization',
    storageBucket: 'ai-text-digitization.firebasestorage.app',
    iosBundleId: 'com.example.demoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmjOram0hmHSXEHpYhpe0ldl_qqKo1_Sg',
    appId: '1:954030564160:web:8fb02f217bfd48eec2d0a5',
    messagingSenderId: '954030564160',
    projectId: 'ai-text-digitization',
    authDomain: 'ai-text-digitization.firebaseapp.com',
    storageBucket: 'ai-text-digitization.firebasestorage.app',
    measurementId: 'G-9HMZV8DQGL',
  );

}